src/Entity/Tournois.php
<?php

namespace App\Entity;

use App\Repository\TournoisRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=TournoisRepository::class)
 */
class Tournois
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */

    private $id_tournois;

    /**
     * @ORM\Column(type="string", length=255)
     *  * @Assert\NotBlank
     */
    private $nom_tournois;

    /**
     * @ORM\Column(type="string", length=255)
     *  * @Assert\NotBlank
     */
    private $rank_tournois;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * * @Assert\Date
     * @var string A "d-m-Y" formatted value
     */
    private $date_tournois;

//    /**
//     * @ORM\Column(type="integer")
//     *  * @Assert\NotBlank
//     *
//     */
//    private $id_match;



    public function getIdTournois(): ?int
    {
        return $this->id_tournois;
    }

    public function setIdTournois(int $id_tournois): self
    {
        $this->id_tournois = $id_tournois;

        return $this;
    }

    public function getNomTournois(): ?string
    {
        return $this->nom_tournois;
    }

    public function setNomTournois(string $nom_tournois): self
    {
        $this->nom_tournois = $nom_tournois;

        return $this;
    }

    public function getRankTournois(): ?string
    {
        return $this->rank_tournois;
    }

    public function setRankTournois(string $rank_tournois): self
    {
        $this->rank_tournois = $rank_tournois;

        return $this;
    }

    public function getDateTournois(): ?string
    {
        return $this->date_tournois;
    }

    public function setDateTournois(string $date_tournois): self
    {
        $this->date_tournois = $date_tournois;

        return $this;
    }
//
//    public function getIdMatch(): ?int
//    {
//        return $this->id_match;
//    }

//    public function setIdMatch(int $id_match): self
//    {
//        $this->id_match = $id_match;
//
//        return $this;
//    }
}

src/Form/TournoisType.php
<?php

namespace App\Form;

use App\Entity\Tournois;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TournoisType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_tournois')
            ->add('rank_tournois')
            ->add('date_tournois')
//            ->add('id_match')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Tournois::class,
        ]);
    }
}

src/Controller/TournoisController.php
<?php

namespace App\Controller;

use App\Entity\Tournois;
use App\Form\TournoisType;
use App\Repository\TournoisRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class TournoisController extends AbstractController
{
    /**
     * @Route("/tournois", name="app_tournois_index", methods={"GET"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function index(TournoisRepository $tournoisRepository): Response
    {
        return $this->render('tournois/index.html.twig', [
            'tournois' => $tournoisRepository->findAll(),
        ]);
    }

    /**
     * @Route("/tournois/new", name="app_tournois_new", methods={"GET", "POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function new(Request $request, TournoisRepository $tournoisRepository): Response
    {
        $tournoi = new Tournois();
        $form = $this->createForm(TournoisType::class, $tournoi);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $tournoisRepository->add($tournoi);
            return $this->redirectToRoute('app_tournois_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('tournois/new.html.twig', [
            'tournoi' => $tournoi,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/tournois/{id}", name="app_tournois_show", methods={"GET"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function show(Tournois $tournoi): Response
    {
        return $this->render('tournois/show.html.twig', [
            'tournoi' => $tournoi,
        ]);
    }

    /**
     * @Route("/tournois/{id}/edit", name="app_tournois_edit", methods={"GET", "POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function edit(Request $request, Tournois $tournoi, TournoisRepository $tournoisRepository): Response
    {
        $form = $this->createForm(TournoisType::class, $tournoi);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $tournoisRepository->add($tournoi);
            return $this->redirectToRoute('app_tournois_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('tournois/edit.html.twig', [
            'tournoi' => $tournoi,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/tournois/{id}", name="app_tournois_delete", methods={"POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function delete(Request $request, Tournois $tournoi, TournoisRepository $tournoisRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$tournoi->getIdTournois(), $request->request->get('_token'))) {
            $tournoisRepository->remove($tournoi);
        }

        return $this->redirectToRoute('app_tournois_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/tournois/_delete_form.html.twig
<form method="post" action="{{ path('app_tournois_delete', {'id': tournoi.idTournois}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tournoi.idTournois) }}">
    <button class="btn d-grid btn-danger text-white">Delete</button>
</form>

templates/tournois/_form.html.twig
{{ form_start(form, {'attr': {'novalidate' :'novalidate' }} ) }}
<div style="display: flex; flex-direction: column;gap: 20px;">
    <div>

        <h5> Nom du tournois</h5>
        {{ form_row(form.nom_tournois,{'label': ' ' ,'attr': {'placeholder': 'Veuillez entrez le nom du tournois' }  } ) }}

    </div>
    <div>
        <h5> Rank du tournois</h5>
        {{ form_row(form.rank_tournois,{'label': ' ' , 'attr': {'placeholder': 'Veuillez entrez le rank du tournois ' }  } ) }}

    </div>
    <div >

        {{ form_row(form.date_tournois) }}
    </div>
{#    <div>#}
{#        <h5> id du match </h5>#}
{#        {{ form_row(form.id_match,{'label': ' ' ,'attr': {'placeholder': 'Veuillez entrez lid du match' }  } ) }}#}

{#    </div>#}

    <button class="btn d-grid btn-danger text-white" >{{ button_label|default('Save') }}</button>
</div>
{{ form_end(form) }}

templates/tournois/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Tournois{% endblock %}

{% block tableau %}
    <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="page-breadcrumb bg-white">
            <div class="row align-items-center">
                <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                    <h4 class="page-title">Users list</h4>
                </div>
                <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                    <div class="d-md-flex">
                        <ol class="breadcrumb ms-auto">



                        </ol>

                    </div>
                </div>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <!-- ============================================================== -->
            <!-- Start Page Content -->
            <!-- ============================================================== -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="white-box">
                        <h3 class="box-title">Users list</h3>

                        <div class="table-responsive">
                            <div style="margin: 6rem 6rem; display: flex; flex-direction: column; justify-content: center; align-items: center; gap: 40px;" >
                        <h1>Edit Tournois</h1>

    {{ include('tournois/_form.html.twig', {'button_label': 'Update'}) }}
                            </div>

    <a href="{{ path('app_tournois_index') }}"> <button class="btn d-grid btn-danger text-white"> back to list  </button> </a>

    {{ include('tournois/_delete_form.html.twig') }}
    </div>
    </div>
    </div>
    </div>
    <!-- ============================================================== -->
    <!-- End PAge Content -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Right sidebar -->
    <!-- ============================================================== -->
    <!-- .right-sidebar -->
    <!-- ============================================================== -->
    <!-- End Right sidebar -->
    <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- footer -->
    <!-- ============================================================== -->
    <footer class="footer text-center">
    </footer>
    <!-- ============================================================== -->
    <!-- End footer -->
    <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Page wrapper  -->
    <!-- ============================================================== -->
    </div>



    </body>
    </html>
{% endblock %}

templates/tournois/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tournois index{% endblock %}

{% block tableau %}
<div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-breadcrumb bg-white">
        <div class="row align-items-center">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                <h4 class="page-title">Users list</h4>
            </div>
            <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                <div class="d-md-flex">
                    <ol class="breadcrumb ms-auto">



                    </ol>

                </div>
            </div>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-sm-12">
                <div class="white-box">
                    <h3 class="box-title">Users list</h3>

                    <div class="table-responsive">

                    <h1>Tournois </h1>

    <table class="table">
        <thead>
            <tr>

                <th>Nom_tournois</th>
                <th>Rank_tournois</th>
                <th>Date_tournois</th>
{#                <th>Id_match</th>#}
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for tournoi in tournois %}
            <tr>

                <td>{{ tournoi.nomTournois }}</td>
                <td>{{ tournoi.rankTournois }}</td>
                <td>{{ tournoi.dateTournois }}</td>
{#                <td>{{ tournoi.idMatch }}</td>#}
                <td>
                    <a href="{{ path('app_tournois_show', {'id': tournoi.idTournois}) }}"> <button class="btn d-grid btn-danger text-white"> show </button> </a>
                    <a href="{{ path('app_tournois_edit', {'id': tournoi.idTournois}) }}"> <button class="btn d-grid btn-danger text-white"> edit  </button></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_tournois_new') }}">Create new</a>
{% endblock %}

templates/tournois/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Tournois{% endblock %}

{% block tableau %}
<div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-breadcrumb bg-white">
        <div class="row align-items-center">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                <h4 class="page-title">Users list</h4>
            </div>
            <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                <div class="d-md-flex">
                    <ol class="breadcrumb ms-auto">



                    </ol>

                </div>
            </div>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-sm-12">
                <div class="white-box">
                    <h3 class="box-title">Users list</h3>

                    <div class="table-responsive">
                        <div style="margin: 6rem 6rem; display: flex; flex-direction: column; justify-content: center; align-items: center; gap: 40px;" >
    <h1>Create new Tournois</h1>

    {{ include('tournois/_form.html.twig') }}
                        </div>
    <a href="{{ path('app_tournois_index') }}"> <button class="btn d-grid btn-danger text-white"> back to list  </button>   </a>
                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right sidebar -->
        <!-- ============================================================== -->
        <!-- .right-sidebar -->
        <!-- ============================================================== -->
        <!-- End Right sidebar -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- footer -->
    <!-- ============================================================== -->
    <footer class="footer text-center">
    </footer>
    <!-- ============================================================== -->
    <!-- End footer -->
    <!-- ============================================================== -->
</div>
    <!-- ============================================================== -->
    <!-- End Page wrapper  -->
    <!-- ============================================================== -->
    </div>



    </body>
    </html>
{% endblock %}

templates/tournois/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tournois{% endblock %}

{% block tableau %}
    <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="page-breadcrumb bg-white">
            <div class="row align-items-center">
                <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                    <h4 class="page-title">Users list</h4>
                </div>
                <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                    <div class="d-md-flex">
                        <ol class="breadcrumb ms-auto">



                        </ol>

                    </div>
                </div>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <!-- ============================================================== -->
            <!-- Start Page Content -->
            <!-- ============================================================== -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="white-box">
                        <h3 class="box-title">Users list</h3>

                        <div class="table-responsive">

                        <h1>Tournois</h1>

    <table class="table">
        <tbody>


            <tr>
                <th>Nom_tournois</th>
                <td>{{ tournoi.nomTournois }}</td>
            </tr>
            <tr>
                <th>Rank_tournois</th>
                <td>{{ tournoi.rankTournois }}</td>
            </tr>
            <tr>
                <th>Date_tournois</th>
                <td>{{ tournoi.dateTournois }}</td>
            </tr>

        </tbody>
    </table>

    <a href="{{ path('app_tournois_index') }}"> <button class="btn d-grid btn-danger text-white"> back to list  </button> </a>

    <a href="{{ path('app_tournois_edit', {'id': tournoi.idTournois}) }}"> <button class="btn d-grid btn-danger text-white"> edit </button> </a>

    {{ include('tournois/_delete_form.html.twig') }}
    </div>
    </div>
    </div>
    </div>
    <!-- ============================================================== -->
    <!-- End PAge Content -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Right sidebar -->
    <!-- ============================================================== -->
    <!-- .right-sidebar -->
    <!-- ============================================================== -->
    <!-- End Right sidebar -->
    <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- footer -->
    <!-- ============================================================== -->
    <footer class="footer text-center">
    </footer>
    <!-- ============================================================== -->
    <!-- End footer -->
    <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Page wrapper  -->
    <!-- ============================================================== -->
    </div>



    </body>
    </html>
{% endblock %}