src/Entity/Match1.php
<?php

namespace App\Entity;

use App\Repository\Match1Repository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=Match1Repository::class)
 */
class Match1
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")

     */

    private $id_match1;

    /**
     * @ORM\Column(type="string", length=255)
     *  * @Assert\NotBlank
     */
    private $nom_equipe1;

    /**
     * @ORM\Column(type="string", length=255)
     *  * @Assert\NotBlank
     * @Assert\NotEqualTo(propertyPath="nom_equipe1",
     * message = "l'equipe 1 ne doit pas etre identique a l'equipe 2."
     * )
     */
    private $nom_equipe2;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @Assert\Date
     * @var string A "d-m-Y" formatted value
     */

    private $date_match1;

    /**
     * @ORM\Column(type="string", length=255)
     *
     *
     */
    private $resultat_match1;

    /**
     * @ORM\Column(type="string", length=255)
     *  * @Assert\NotBlank
     */
    private $lieu_match1;

    /**
     * @ORM\Column(type="string", length=255)
     *
     *   * @Assert\Email(
     *     message = "The email '{{ value }}' is not a valid email."
     * )
     *   @Assert\NotBlank
     */
    private $Email_lieu;


    public function getIdMatch1(): ?int
    {
        return $this->id_match1;
    }

    public function setIdMatch1(int $id_match1): self
    {
        $this->id_match1 = $id_match1;

        return $this;
    }

    public function getNomEquipe1(): ?string
    {
        return $this->nom_equipe1;
    }

    public function setNomEquipe1(string $nom_equipe1): self
    {
        $this->nom_equipe1 = $nom_equipe1;

        return $this;
    }

    public function getNomEquipe2(): ?string
    {
        return $this->nom_equipe2;
    }

    public function setNomEquipe2(string $nom_equipe2): self
    {
        $this->nom_equipe2 = $nom_equipe2;

        return $this;
    }

    public function getDateMatch1(): ?string
    {
        return $this->date_match1;
    }

    public function setDateMatch1(string $date_match1): self
    {
        $this->date_match1 = $date_match1;

        return $this;
    }

    public function getResultatMatch1(): ?string
    {
        return $this->resultat_match1;
    }

    public function setResultatMatch1(string $resultat_match1): self
    {
        $this->resultat_match1 = $resultat_match1;

        return $this;
    }

    public function getLieuMatch1(): ?string
    {
        return $this->lieu_match1;
    }

    public function setLieuMatch1(string $lieu_match1): self
    {
        $this->lieu_match1 = $lieu_match1;

        return $this;
    }

    public function getEmailLieu(): ?string
    {
        return $this->Email_lieu;
    }

    public function setEmailLieu(string $Email_lieu): self
    {
        $this->Email_lieu = $Email_lieu;

        return $this;
    }
}

src/Form/Match1Type.php
<?php

namespace App\Form;

use App\Entity\Match1;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class Match1Type extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_equipe1')
            ->add('nom_equipe2')
            ->add('date_match1' )
            ->add('resultat_match1')
            ->add('lieu_match1')
            ->add('Email_lieu')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Match1::class,
        ]);
    }
}

src/Controller/Match1Controller.php
<?php

namespace App\Controller;

use App\Entity\Match1;
use App\Form\MailPlaceType;
use App\Form\Match1Type;
use App\Repository\Match1Repository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use Symfony\Component\HttpFoundation\ResponseHeaderBag;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Component\Security\Csrf\TokenGenerator\TokenGeneratorInterface;


class Match1Controller extends Controller
{
    /**
     * @Route("/match", name="app_match1_index", methods={"GET"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function index(Match1Repository $match1Repository ,Request $request): Response
    {

        $matchs = $match1Repository->findAll();
        $nbrPage=count($matchs);
        $matchs  = $this->get('knp_paginator')->paginate(
            $matchs,
            $request->query->get('page', 1),
        3);

        dump($nbrPage);
        if($nbrPage%3==0)
        {
            $nbrPage=$nbrPage/3; 
        }
        else{
            $nbrPage=intval($nbrPage/3)+1;

        }
        dump($nbrPage);
        return $this->render('match1/index.html.twig', [
            'matchs' => $matchs,
            'nbrPage'=>$nbrPage
        ]);
    }

    /**
     * @Route("/match/new", name="app_match1_new", methods={"GET", "POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function new(Request $request, Match1Repository $match1Repository): Response
    {
        $match1 = new Match1();
        $form = $this->createForm(Match1Type::class, $match1);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $match1Repository->add($match1);

            return $this->redirectToRoute('app_match1_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('match1/new.html.twig', [
            'match1' => $match1,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/match/{id_match1}", name="app_match1_show", methods={"GET"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function show(Match1 $match1): Response
    {
        return $this->render('match1/show.html.twig', [
            'match1' => $match1,
        ]);
    }

    /**
     * @Route("/match/{id_match1}/edit", name="app_match1_edit", methods={"GET", "POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function edit(Request $request, Match1 $match1, Match1Repository $match1Repository): Response
    {
        $form = $this->createForm(Match1Type::class, $match1);
//        $match1->setResultatMatch1('undefined');

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $match1Repository->add($match1);
            return $this->redirectToRoute('app_match1_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('match1/edit.html.twig', [
            'match1' => $match1,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/match/{id_match1}", name="app_match1_delete", methods={"POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function delete(Request $request, Match1 $match1, Match1Repository $match1Repository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$match1->getIdMatch1(), $request->request->get('_token'))) {
            $match1Repository->remove($match1);
        }

        return $this->redirectToRoute('app_match1_index', [], Response::HTTP_SEE_OTHER);
    }

    /**
     * @Route("/generatePDF", name="generatePDF")
     */
    public function generatePDF(Request $request, Match1Repository $match1Repository): Response
    {
    //    dd($startDate,$endDate);
$matchs = $match1Repository->findAll();



$inputFileName = '../public/template.xlsx';

    /** Load $inputFileName to a Spreadsheet Object  **/
$spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load($inputFileName);


    /* @var $sheet \PhpOffice\PhpSpreadsheet\Writer\Xlsx\Worksheet */
$sheet = $spreadsheet->getActiveSheet();
$sheet->setTitle("Month Resume");



$line = 13;
foreach ($matchs as $mtch) {

$sheet->setCellValue('A'.$line, $mtch->getNomEquipe1());
$sheet->setCellValue('B'.$line, $mtch->getNomEquipe2());
$sheet->setCellValue('C'.$line, $mtch->getDateMatch1());
$sheet->setCellValue('D'.$line, $mtch->getResultatMatch1());

$line = $line+1;
}



// Create your Office 2007 Excel (XLSX Format)
$writer = new Xlsx($spreadsheet);

// Create a Temporary file in the system
$fileName = 'resume.xlsx';
$temp_file = tempnam(sys_get_temp_dir(), $fileName);

// Create the excel file in the tmp directory of the system
$writer->save($temp_file);

// Return the excel file as an attachment
return $this->file($temp_file, $fileName, ResponseHeaderBag::DISPOSITION_INLINE);

}
    /**
     * @Route("/place", name="place")
     */
    public function place(Request $request, Match1Repository $rep, MailerInterface $mailer, TokenGeneratorInterface $tokenGeneratorInterface)
    {
        $form = $this->createForm(MailPlaceType::class);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid())
        {
            $data = $form->getData();
            $match1 = $rep->findOneBy(['Email_lieu'=>$data['email']]);
            $email = (new TemplatedEmail())
                ->from('primeleagueesports@gmail.com')
                ->to($match1->getEmailLieu())
                ->subject('Demande de collaboration ')
                ->htmlTemplate('match1/template.html.twig')
                ;

            $mailer->send($email);
            return $this->redirectToRoute('app_match1_index');

        }

        return $this->render('match1/MailPlace.html.twig' , ['emailForm' => $form->createView()]);
    }
}

templates/match1/MailPlace.html.twig
{% extends 'base.html.twig' %}

{% block title %}Match{% endblock %}

{% block tableau %}

<div class="container-fluid">
    <div class="row h-100 align-items-center justify-content-center" style="min-height: 100vh;">
        <div class="col-12 col-sm-8 col-md-6 col-lg-5 col-xl-4">
            <div class="bg-light rounded p-4 p-sm-5 my-4 mx-3">
                <div class="section-title" data-aos="fade-up">
                    <h2>Email au lieu</h2>
                </div>
                {{ form(emailForm) }}
            </div>
        </div>
    </div>
</div>
{%endblock %}

templates/match1/_delete_form.html.twig
<form method="post" action="{{ path('app_match1_delete', {'id_match1': match1.idMatch1}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ match1.idMatch1) }}">
    <button class="btn d-grid btn-danger text-white">Delete</button>
</form>

templates/match1/_form.html.twig
{{ form_start(form, {'attr': {'novalidate' :'novalidate' }} ) }}
<div style="display: flex; flex-direction: column;gap: 20px;">
    <div>

        <h5> Nom de l'equipe 1</h5>
        {{ form_row(form.nom_equipe1,{'label': ' ' ,'attr': {'placeholder': 'Veuillez entrez votre Nom equipe 1' }  } ) }}

    </div>
    <div>
        <h5> Nom de l'equipe 2</h5>
        {{ form_row(form.nom_equipe2,{'label': ' ' , 'attr': {'placeholder': 'Veuillez entrez votre Nom equipe 2' }  } ) }}

    </div>
    <div >
        {{ form_row(form.date_match1) }}
    </div>
    <div>
        <h5> Resultat du match  </h5>
        {{ form_row(form.resultat_match1,{'label': ' ' ,'attr': {'placeholder': 'Veuillez entrez le Resultat' }  } ) }}

    </div>
    <div>
        <h5> Lieu du match </h5>
        {{ form_row(form.lieu_match1,{'label': ' ','attr': {'placeholder': 'Veuillez entrez le lieu du match' }  } ) }}


    </div>
    <div>
        <h5> L'email de lieu de match</h5>
        {{ form_row(form.Email_lieu,{'label': ' ','attr': {'placeholder': 'Veuillez entrez lemail du match' }  } ) }}


    </div>
</div>
    <button class="btn d-grid btn-danger text-white" >{{ button_label|default('Save') }}</button>

</div>
{{ form_end(form) }}

templates/match1/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Match1{% endblock %}

{% block tableau %}
    <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="page-breadcrumb bg-white">
            <div class="row align-items-center">
                <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                    <h4 class="page-title">Users list</h4>
                </div>
                <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                    <div class="d-md-flex">
                        <ol class="breadcrumb ms-auto">



                        </ol>

                    </div>
                </div>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <!-- ============================================================== -->
            <!-- Start Page Content -->
            <!-- ============================================================== -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="white-box">
                        <h3 class="box-title">Users list</h3>

                        <div class="table-responsive">

                        <h1>Edit Match1</h1>

    {{ include('match1/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_match1_index') }}"> <button class="btn d-grid btn-danger text-white"> back to list  </button> </a>

    {{ include('match1/_delete_form.html.twig') }}
    </div>
    </div>
    </div>
    </div>
    <!-- ============================================================== -->
    <!-- End PAge Content -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Right sidebar -->
    <!-- ============================================================== -->
    <!-- .right-sidebar -->
    <!-- ============================================================== -->
    <!-- End Right sidebar -->
    <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- footer -->
    <!-- ============================================================== -->
    <footer class="footer text-center">
    </footer>
    <!-- ============================================================== -->
    <!-- End footer -->
    <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Page wrapper  -->
    <!-- ============================================================== -->
    </div>



    </body>
    </html>
{% endblock %}

templates/match1/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Match{% endblock %}

{% block tableau %}
<div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-breadcrumb bg-white">
        <div class="row align-items-center">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                <h4 class="page-title">Users list</h4>
            </div>
            <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                <div class="d-md-flex">
                    <ol class="breadcrumb ms-auto">



                    </ol>

                </div>
            </div>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-sm-12">
                <div class="white-box">
                    <h3 class="box-title">Users list</h3>

                    <div class="table-responsive">
    <h1>Match1 </h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id_match1</th>
                <th>Nom_equipe1</th>
                <th>Nom_equipe2</th>
                <th>Date_match1</th>
                <th>Resultat_match1</th>
                <th>Lieu_match1</th>
                <th>Email_lieu</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for match1 in matchs %}
            <tr>
                <td>{{ match1.idMatch1 }}</td>
                <td>{{ match1.nomEquipe1 }}</td>
                <td>{{ match1.nomEquipe2 }}</td>
                <td>{{ match1.dateMatch1 }}</td>
                <td>{{ match1.resultatMatch1 }}</td>
                <td>{{ match1.lieuMatch1 }}</td>
                <td>{{ match1.EmailLieu }}</td>
                <td>
                    <a href="{{ path('app_match1_show', {'id_match1': match1.idMatch1}) }}">  <button class="btn d-grid btn-danger text-white"> show  </button>  </a>
                    <a href="{{ path('app_match1_edit', {'id_match1': match1.idMatch1}) }}"> <button class="btn d-grid btn-danger text-white"> edit  </button> </a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_match1_new') }}"> <button class="btn d-grid btn-danger text-white"> Create new  </button> </a>
                        <a href="{{ path('generatePDF') }}"> <button class="btn d-grid btn-danger text-white"> GENERATE Excel  </button> </a>
                        <a href="{{ path('place') }}"> <button class="btn d-grid btn-danger text-white"> Envoyer un E-mail  </button> </a>

                    </div>
                </div>
            </div>
        </div>

        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right sidebar -->
        <!-- ============================================================== -->
        <!-- .right-sidebar -->
        <!-- ============================================================== -->
        <!-- End Right sidebar -->
        <!-- ============================================================== -->
    </div>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% for i in 1..nbrPage %}
            <li class="page-item"><a class="page-link" href="http://127.0.0.1:8000/match/?page= {{ i }} ">{{ i }} </a></li>
                    {% endfor %}
                    </ul>
                </nav>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- footer -->
    <!-- ============================================================== -->
    <footer class="footer text-center">
    </footer>
    <!-- ============================================================== -->
    <!-- End footer -->
    <!-- ============================================================== -->
</div>
    <!-- ============================================================== -->
    <!-- End Page wrapper  -->
    <!-- ============================================================== -->
    </div>



    </body>
    </html>
{% endblock %}

templates/match1/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Match1{% endblock %}

{% block tableau %}
<div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-breadcrumb bg-white">
        <div class="row align-items-center">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                <h4 class="page-title">Users list</h4>
            </div>
            <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                <div class="d-md-flex">
                    <ol class="breadcrumb ms-auto">



                    </ol>

                </div>
            </div>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-sm-12">
                <div class="white-box">
                    <h3 class="box-title">Users list</h3>

                    <div class="table-responsive">
                        <div style="margin: 6rem 6rem; display: flex; flex-direction: column; justify-content: center; align-items: center; gap: 40px;" >
    <h1>Créer un noveau match </h1>

    {{ include('match1/_form.html.twig') }}
                        </div>
    <a href="{{ path('app_match1_index') }}"> <button class="btn d-grid btn-danger text-white"> back to list  </button> </a>
                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right sidebar -->
        <!-- ============================================================== -->
        <!-- .right-sidebar -->
        <!-- ============================================================== -->
        <!-- End Right sidebar -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- footer -->
    <!-- ============================================================== -->
    <footer class="footer text-center">
    </footer>
    <!-- ============================================================== -->
    <!-- End footer -->
    <!-- ============================================================== -->
</div>
    <!-- ============================================================== -->
    <!-- End Page wrapper  -->
    <!-- ============================================================== -->
    </div>



    </body>
    </html>
{% endblock %}

templates/match1/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Match1{% endblock %}

{% block tableau %}
    <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="page-breadcrumb bg-white">
            <div class="row align-items-center">
                <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                    <h4 class="page-title">Users list</h4>
                </div>
                <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                    <div class="d-md-flex">
                        <ol class="breadcrumb ms-auto">



                        </ol>

                    </div>
                </div>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <!-- ============================================================== -->
            <!-- Start Page Content -->
            <!-- ============================================================== -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="white-box">
                        <h3 class="box-title">Users list</h3>

                        <div class="table-responsive">

                        <h1>Match1</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id_match1</th>
                <td>{{ match1.idMatch1 }}</td>
            </tr>
            <tr>
                <th>Nom_equipe1</th>
                <td>{{ match1.nomEquipe1 }}</td>
            </tr>
            <tr>
                <th>Nom_equipe2</th>
                <td>{{ match1.nomEquipe2 }}</td>
            </tr>
            <tr>
                <th>Date_match1</th>
                <td>{{ match1.dateMatch1 }}</td>
            </tr>
            <tr>
                <th>Resultat_match1</th>
                <td>{{ match1.resultatMatch1 }}</td>
            </tr>
            <tr>
                <th>Lieu_match1</th>
                <td>{{ match1.lieuMatch1 }}</td>
            </tr>
            <tr>
                <th>Email_lieu</th>
                <td>{{ match1.EmailLieu }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_match1_index') }}"> <button class="btn d-grid btn-danger text-white"> back to list </button> </a>

    <a href="{{ path('app_match1_edit', {'id_match1': match1.idMatch1}) }}"> <button class="btn d-grid btn-danger text-white">edit  </button></a>

    {{ include('match1/_delete_form.html.twig') }}
    </div>
    </div>
    </div>
    </div>
    <!-- ============================================================== -->
    <!-- End PAge Content -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Right sidebar -->
    <!-- ============================================================== -->
    <!-- .right-sidebar -->
    <!-- ============================================================== -->
    <!-- End Right sidebar -->
    <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- footer -->
    <!-- ============================================================== -->
    <footer class="footer text-center">
    </footer>
    <!-- ============================================================== -->
    <!-- End footer -->
    <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Page wrapper  -->
    <!-- ============================================================== -->
    </div>



    </body>
    </html>
{% endblock %}