src/Entity/Categorie.php
<?php

namespace App\Entity;

use App\Repository\CategorieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * @ORM\Entity(repositoryClass=CategorieRepository::class)
 * @Vich\Uploadable
 */
class Categorie
{

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * 
     */
    private $id_categorie;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="s il vous plaît choisir un nom ")
     * 
     */
    private $nom_categorie;

     /**
     * @Vich\UploadableField(mapping="product_images", fileNameProperty="image")
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=1000)
     * @var string
     * 
     */
    private $image;

   

    /**
     * @ORM\OneToMany(targetEntity=Produits::class, mappedBy="id_categorie")
     * 
     */
    private $produit;

    public function __construct()
    {
        $this->produit = new ArrayCollection();
    }


    public function getIdCategorie(): ?int
    {
        return $this->id_categorie;
    }

    public function setIdCategorie(int $id_categorie): self
    {
        $this->id_categorie = $id_categorie;

        return $this;
    }

    public function getNomCategorie(): ?string
    {
        return $this->nom_categorie;
    }

    public function setNomCategorie(string $nom_categorie): self
    {
        $this->nom_categorie = $nom_categorie;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string$image): self
    {
        $this->image = $image;

        return $this;
    }
    /**
     * 
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $image
     */
    public function setImageFile(File $image = null): void
    {
        $this->imageFile = $image;

        if ($image) {
            
            echo"image vide";
        }

    }

    public function getImageFile()
    {
        return $this->imageFile;
    }
    
    /**
     * @return Collection<int, Produits>
     */
    public function getProduit(): Collection
    {
        return $this->produit;
    }

    public function addProduit(Produits $produit): self
    {
        if (!$this->produit->contains($produit)) {
            $this->produit[] = $produit;
            $produit->setIdCategorie($this);
        }

        return $this;
    }

    public function removeProduit(Produits $produit): self
    {
        if ($this->produit->removeElement($produit)) {
            // set the owning side to null (unless already changed)
            if ($produit->getIdCategorie() === $this) {
                $produit->setIdCategorie(null);
            }
        }

        return $this;
    }

    public function __toString() 
{
    return (string) $this->nom_categorie; 
}

}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use PhpParser\Node\Scalar\String_;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */

    private $id_user;

    /**
     * @ORM\Column(type="string", length=255)
     *@Assert\NotBlank()
     */
    private $nom_user;

    /**
     * @ORM\Column(type="string", length=255)
     *@Assert\NotBlank()
     */
    private $prenom_user;

    /**
     * @ORM\Column(type="integer")
     *
     * @Assert\NotNull
     */
    private $tel_user;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(
     *     message = "The email '{{ value }}' is not a valid email."
     * )
     */
    private $email_user;

    /**
     * @var string The hashed password
     * @ORM\Column(type="string", length=255)
     * * @Assert\Length(
     *      min = 4,
     *
     *      minMessage = "Votre mot de passe doit contenir minimum {{ limit }} characteres"
     *
     * )
     */
    private $mdp_user;

    /**
     * @ORM\Column(type="json")
     */
    private $role=[];

    /**
     * @ORM\Column(type="string", length=255)
     *
     */
    private $pdp;


    public function getIdUser(): ?int
    {
        return $this->id_user;
    }

    public function setIdUser(int $id_user): self
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function getNomUser(): ?string
    {
        return $this->nom_user;
    }

    public function setNomUser(string $nom_user): self
    {
        $this->nom_user = $nom_user;

        return $this;
    }

    public function getPrenomUser(): ?string
    {
        return $this->prenom_user;
    }

    public function setPrenomUser(string $prenom_user): self
    {
        $this->prenom_user = $prenom_user;

        return $this;
    }

    public function getTelUser(): ?int
    {
        return $this->tel_user;
    }

    public function setTelUser(int $tel_user): self
    {
        $this->tel_user = $tel_user;

        return $this;
    }

    public function getEmailUser(): ?string
    {
        return $this->email_user;
    }

    public function setEmailUser(string $email_user): self
    {
        $this->email_user = $email_user;

        return $this;
    }

    public function getMdpUser(): ?string
    {
        return $this->mdp_user;
    }

    public function setMdpUser(string $mdp_user): self
    {
        $this->mdp_user = $mdp_user;

        return $this;
    }

    public function getRole(): ?array
    {
        return $this->role;
    }

    public function setRole(string $role): self
    {
        $this->role = $role;

        return $this;
    }

    public function getPdp()
    {
        return $this->pdp;
    }

    public function setPdp($pdp)
    {
        $this->pdp = $pdp;

        return $this;
    }

    public function getRoles()
    {
        $role= $this->role;
        $role[] = 'ROLE_USER';

        return array_unique($role);
    }

    public function getPassword()
    {
        return $this->mdp_user;
    }

    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    public function getUsername()
    {
        return $this->email_user;
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    public function __toString():string
    {
        return $this->id_user.' | '.$this->nom_user.' '.$this->getPrenomUser();
    }


    protected $captchaCode;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $reset_token;

    public function getCaptchaCode()
    {
        return $this->captchaCode;
    }

    public function setCaptchaCode($captchaCode)
    {
        $this->captchaCode = $captchaCode;
    }

    public function getResetToken(): ?string
    {
        return $this->reset_token;
    }

    public function setResetToken(?string $reset_token): self
    {
        $this->reset_token = $reset_token;

        return $this;
    }
}

src/Form/CategorieType.php
<?php

namespace App\Form;

use App\Entity\Categorie;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichImageType;

class CategorieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_categorie',TextType::class,[
                'required'=>false,
            ])
            ->add('imageFile',VichImageType::class,[
                'required'=>false,
                'empty_data' => ''
            ])
            ->add('ajouter',SubmitType::class,)
            
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Categorie::class,
        ]);
    }
}

src/Controller/CategorieController.php
<?php

namespace App\Controller;

use App\Entity\Categorie;
use App\Form\CategorieType;
use App\Repository\CategorieRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;


/**
 * 
 */
class CategorieController extends AbstractController
{
    /**
     * @Route("/categorie/list", name="app_categorie_index", methods={"GET"})
     */
    
    public function index(CategorieRepository $categorieRepository): Response
    {
        
        return $this->render('categorie/index.html.twig', [
            'categories' => $categorieRepository->findAll(),
        ]);
        
    }

    /**
     * @Route("/categorie/add", name="app_categorie_new")
     */
    public function new(Request $request): Response
    {
        $categorie = new Categorie();
        $form = $this->createForm(CategorieType::class, $categorie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($categorie);
            $em->flush();
           
            return $this->redirectToRoute('app_categorie_index');
        }

        return $this->render('categorie/new.html.twig', [
            'categorie' => $categorie,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/categorie/{id_categorie}", name="app_categorie_show", methods={"GET"})
     */
    public function show(Categorie $categorie): Response
    {
        return $this->render('categorie/show.html.twig', [
            'categorie' => $categorie,
        ]);
    }

    /**
     * @Route("/categorie/edit/{id_categorie}", name="app_categorie_edit")
     */
    public function edit(Request $request, $id_categorie): Response
    {   $categorie=$this->getDoctrine()->getManager()->getRepository(Categorie::class)->find($id_categorie);
        $form = $this->createForm(CategorieType::class ,$categorie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em=$this->getDoctrine()->getManager();
            $em->flush();
            return $this->redirectToRoute('app_categorie_index');
        }

        return $this->render('categorie/edit.html.twig', [
            
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/Categorie/delete/{id_categorie}", name="app_categorie_delete")
     */
    public function delete(Request $request, Categorie $categorie, CategorieRepository $categorieRepository): Response
    {
        $em=$this->getDoctrine()->getManager();
        $em->remove($categorie);
        $em->flush();
        return $this->redirectToRoute('app_categorie_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/categorie/_delete_form.html.twig
<form method="post"   onsubmit="return confirm('Are you sure you want to delete this item?');">
    
</form>

templates/categorie/_form.html.twig
 <div class="col-lg-8 col-xlg-9 col-md-12">
                        <div class="card">
                            <div class="card-body">
                                {{ form_start(form) }}
                                
                                    <div class="form-group mb-4">
                                        <label class="col-md-12 p-0">Nom categorie</label>
                                        <div class="col-md-12 border-bottom p-0">
                                            {{form_widget(form.nom_categorie,{'attr':{'class':'form-control'}})}}
                                                {{ form_errors(form.nom_categorie) }}
                                            </div>
                                    </div>
                                    
                                    <div class="form-group mb-4">
                                        <label class="col-md-12 p-0">Image</label>
                                        <div class="col-md-12 border-bottom p-0">
                                            {{form_widget(form.imageFile,{'attr':{'class':'form-control'}})}}
                                                {{ form_errors(form.imageFile) }}
                                            </div>
                                    </div>

                                    <div class="form-group mb-4">
                                        <div class="col-sm-12" >
                                            {{form_widget(form.ajouter,{'attr':{'class':'btn btn-success'}})}}
                                        </div>
                                    </div>
                                {{ form_end(form) }}
                            </div>
                        </div>
                    </div>

templates/categorie/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier Categorie{% endblock %}

{% block tableau %}
    <div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-breadcrumb bg-white">
        <div class="row align-items-center">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                <h4 class="page-title">Gérer catégories</h4>
            </div>
            <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                <div class="d-md-flex">
                    <ol class="breadcrumb ms-auto">

                        {% if app.user %}
                            <div class="mb-3">
                                <li>You are logged in as {{ app.user.emailUser }}, <a href="{{ path('app_logout') }}">Logout</a></li>
                            </div>
                        {% endif %}

                    </ol>

                </div>
            </div>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-sm-12">
                <div class="white-box">
                    <h3 class="box-title">Modifier catégorie</h3>

                    <div class="table-responsive">
                    
    {{ include('categorie/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_categorie_index') }}">retour à la liste</a>

    {{ include('categorie/_delete_form.html.twig') }}

    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right sidebar -->
        <!-- ============================================================== -->
        <!-- .right-sidebar -->
        <!-- ============================================================== -->
        <!-- End Right sidebar -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- footer -->
    <!-- ============================================================== -->
    <footer class="footer text-center">
    </footer>
    <!-- ============================================================== -->
    <!-- End footer -->
    <!-- ============================================================== -->
</div>
    <!-- ============================================================== -->
    <!-- End Page wrapper  -->
    <!-- ============================================================== -->
    </div>



    </body>
    </html>
{% endblock %}

templates/categorie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste Des Catégories{% endblock %}

{% block tableau %}
    <div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-breadcrumb bg-white">
        <div class="row align-items-center">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                <h4 class="page-title">Gérer catégories</h4>
            </div>
            <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                <div class="d-md-flex">
                    <ol class="breadcrumb ms-auto">
                    </ol>
                </div>
            </div>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-sm-12">
                <div class="white-box">
                    <h3 class="box-title">Liste des catégories</h3>

                    <div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>Reference de categorie</th>
                <th>Nom categorie</th>
                <th>Image</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for categorie in categories %}
            <tr>
                <td>{{ categorie.idCategorie }}</td>
                <td>{{ categorie.nomCategorie }}</td>
                {%if categorie.image%}
                <td><img src="{{vich_uploader_asset(categorie,'imageFile')}}"width="100" height="100"></td>
                {%endif%}
                <td>
                    <a href="{{ path('app_categorie_delete', {'id_categorie': categorie.idCategorie}) }}"class="btn btn-danger">Supprimer</a>
                    <a href="{{ path('app_categorie_edit', {'id_categorie': categorie.idCategorie}) }}"class="btn btn-success">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_categorie_new') }}"class="btn btn-link">Ajouter une nouvelle catégorie</a>
    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right sidebar -->
        <!-- ============================================================== -->
        <!-- .right-sidebar -->
        <!-- ============================================================== -->
        <!-- End Right sidebar -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- footer -->
    <!-- ============================================================== -->
    <footer class="footer text-center">
    </footer>
    <!-- ============================================================== -->
    <!-- End footer -->
    <!-- ============================================================== -->
</div>
    <!-- ============================================================== -->
    <!-- End Page wrapper  -->
    <!-- ============================================================== -->
    </div>

{% endblock %}

templates/categorie/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter Categorie{% endblock %}

{% block tableau %}
    <div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-breadcrumb bg-white">
        <div class="row align-items-center">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                <h4 class="page-title">Gérer catégories</h4>
            </div>
            <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                <div class="d-md-flex">
                    <ol class="breadcrumb ms-auto">
                    </ol>
                </div>
            </div>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-sm-12">
                <div class="white-box">
                    <h3 class="box-title">Ajouter catégories</h3>

                    <div class="table-responsive">

    {{ include('categorie/_form.html.twig') }}
     <div class="card-body p-3">
     </div>
    <a href="{{ path('app_categorie_index') }}""class="btn btn-link">Retour à la liste</a>
   
    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right sidebar -->
        <!-- ============================================================== -->
        <!-- .right-sidebar -->
        <!-- ============================================================== -->
        <!-- End Right sidebar -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- footer -->
    <!-- ============================================================== -->
    <footer class="footer text-center">
    </footer>
    <!-- ============================================================== -->
    <!-- End footer -->
    <!-- ============================================================== -->
</div>
    <!-- ============================================================== -->
    <!-- End Page wrapper  -->
    <!-- ============================================================== -->
    </div>



    </body>
    </html>
{% endblock %}

templates/categorie/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Categorie{% endblock %}

{% block body %}
    <h1>Categorie</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id_categorie</th>
                <td>{{ categorie.idCategorie }}</td>
            </tr>
            <tr>
                <th>Nom_categorie</th>
                <td>{{ categorie.nomCategorie }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ categorie.image }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_categorie_index') }}">retour à la liste</a>

    <a href="{{ path('app_categorie_edit', {'id_categorie': categorie.id_categorie}) }}">edit</a>

    {{ include('categorie/_delete_form.html.twig') }}
{% endblock %}