src/Entity/Blog.php
<?php

namespace App\Entity;

use App\Repository\BlogRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass=BlogRepository::class)
 */
class Blog
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */

    private $id_blog;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email_publisher;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre_blog;

    /**
     * @ORM\Column(type="text", length=65535)
     */
    private $contenu_blog;

    /**
     * @ORM\Column(type="datetime")
     *  @Gedmo\Timestampable(on="create")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     *  @Gedmo\Timestampable(on="update")
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image_blog;


    public function getIdBlog(): ?int
    {
        return $this->id_blog;
    }

    public function setIdBlog(int $id_blog): self
    {
        $this->id_blog = $id_blog;

        return $this;
    }

    public function getEmailPublisher(): ?string
    {
        return $this->email_publisher;
    }

    public function setEmailPublisher(string $email_publisher): self
    {
        $this->email_publisher = $email_publisher;

        return $this;
    }

    public function getTitreBlog(): ?string
    {
        return $this->titre_blog;
    }

    public function setTitreBlog(string $titre_blog): self
    {
        $this->titre_blog = $titre_blog;

        return $this;
    }

    public function getContenuBlog(): ?string
    {
        return $this->contenu_blog;
    }

    public function setContenuBlog(string $contenu_blog): self
    {
        $this->contenu_blog = $contenu_blog;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getImageBlog(): ?string
    {
        return $this->image_blog;
    }

    public function setImageBlog(string $image_blog): self
    {
        $this->image_blog = $image_blog;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use PhpParser\Node\Scalar\String_;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */

    private $id_user;

    /**
     * @ORM\Column(type="string", length=255)
     *@Assert\NotBlank()
     */
    private $nom_user;

    /**
     * @ORM\Column(type="string", length=255)
     *@Assert\NotBlank()
     */
    private $prenom_user;

    /**
     * @ORM\Column(type="integer")
     *
     * @Assert\NotNull
     */
    private $tel_user;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(
     *     message = "The email '{{ value }}' is not a valid email."
     * )
     */
    private $email_user;

    /**
     * @var string The hashed password
     * @ORM\Column(type="string", length=255)
     * * @Assert\Length(
     *      min = 4,
     *
     *      minMessage = "Votre mot de passe doit contenir minimum {{ limit }} characteres"
     *
     * )
     */
    private $mdp_user;

    /**
     * @ORM\Column(type="json")
     */
    private $role=[];

    /**
     * @ORM\Column(type="string", length=255)
     *
     */
    private $pdp;


    public function getIdUser(): ?int
    {
        return $this->id_user;
    }

    public function setIdUser(int $id_user): self
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function getNomUser(): ?string
    {
        return $this->nom_user;
    }

    public function setNomUser(string $nom_user): self
    {
        $this->nom_user = $nom_user;

        return $this;
    }

    public function getPrenomUser(): ?string
    {
        return $this->prenom_user;
    }

    public function setPrenomUser(string $prenom_user): self
    {
        $this->prenom_user = $prenom_user;

        return $this;
    }

    public function getTelUser(): ?int
    {
        return $this->tel_user;
    }

    public function setTelUser(int $tel_user): self
    {
        $this->tel_user = $tel_user;

        return $this;
    }

    public function getEmailUser(): ?string
    {
        return $this->email_user;
    }

    public function setEmailUser(string $email_user): self
    {
        $this->email_user = $email_user;

        return $this;
    }

    public function getMdpUser(): ?string
    {
        return $this->mdp_user;
    }

    public function setMdpUser(string $mdp_user): self
    {
        $this->mdp_user = $mdp_user;

        return $this;
    }

    public function getRole(): ?array
    {
        return $this->role;
    }

    public function setRole(string $role): self
    {
        $this->role = $role;

        return $this;
    }

    public function getPdp()
    {
        return $this->pdp;
    }

    public function setPdp($pdp)
    {
        $this->pdp = $pdp;

        return $this;
    }

    public function getRoles()
    {
        $role= $this->role;
        $role[] = 'ROLE_USER';

        return array_unique($role);
    }

    public function getPassword()
    {
        return $this->mdp_user;
    }

    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    public function getUsername()
    {
        return $this->email_user;
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    public function __toString():string
    {
        return $this->id_user.' | '.$this->nom_user.' '.$this->getPrenomUser();
    }


    protected $captchaCode;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $reset_token;

    public function getCaptchaCode()
    {
        return $this->captchaCode;
    }

    public function setCaptchaCode($captchaCode)
    {
        $this->captchaCode = $captchaCode;
    }

    public function getResetToken(): ?string
    {
        return $this->reset_token;
    }

    public function setResetToken(?string $reset_token): self
    {
        $this->reset_token = $reset_token;

        return $this;
    }
}

src/Controller/BlogFController.php
<?php

namespace App\Controller;

use App\Entity\Blog;
use App\Form\Blog1Type;
use App\Repository\BlogRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/blogf")
 */
class BlogFController extends AbstractController
{
    /**
     * @Route("/", name="app_blog_f_index", methods={"GET"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function index(BlogRepository $blogRepository): Response
    {
        return $this->render('blog_f/index.html.twig', [
            'blogs' => $blogRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_blog_f_new", methods={"GET", "POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function new(Request $request, BlogRepository $blogRepository): Response
    {
        $blog = new Blog();
        $form = $this->createForm(Blog1Type::class, $blog);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $blogRepository->add($blog);
            return $this->redirectToRoute('app_blog_f_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('blog_f/new.html.twig', [
            'blog' => $blog,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id_blog}", name="app_blog_f_show", methods={"GET"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function show(Blog $blog): Response
    {
        return $this->render('blog_f/show.html.twig', [
            'blog' => $blog,
        ]);
    }

    /**
     * @Route("/{id_blog}/edit", name="app_blog_f_edit", methods={"GET", "POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function edit(Request $request, Blog $blog, BlogRepository $blogRepository): Response
    {
        $form = $this->createForm(Blog1Type::class, $blog);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $blogRepository->add($blog);
            return $this->redirectToRoute('app_blog_f_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('blog_f/edit.html.twig', [
            'blog' => $blog,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id_blog}", name="app_blog_f_delete", methods={"POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function delete(Request $request, Blog $blog, BlogRepository $blogRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$blog->getId_blog(), $request->request->get('_token'))) {
            $blogRepository->remove($blog);
        }

        return $this->redirectToRoute('app_blog_f_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/blog_f/_delete_form.html.twig
<form method="post" action="{{ path('app_blog_f_delete', {'id_blog': blog.id_blog}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ blog.id_blog) }}">
   <a >
    <button class="btn btn-outline-warning" target="_blank"  >Delete</button>
   </a>
</form>

templates/blog_f/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/blog_f/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Blog{% endblock %}

{% block body %}
    <h1>Edit Blog</h1>

    {{ include('blog_f/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_blog_f_index') }}">back to list</a>

    {{ include('blog_f/_delete_form.html.twig') }}
{% endblock %}

templates/blog_f/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Blogs{% endblock %}

{% block tableau %}
<div class="page-wrapper">
    <div class="page-breadcrumb bg-white">
        <div class="row align-items-center">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">

            </div>
            <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                <div class="d-md-flex">
                    <ol class="breadcrumb ms-auto">

                        {% if app.user %}
                            <div class="mb-3">
                                <li>You are logged in as {{ app.user.emailUser }}, <a class="btn btn-outline-warning" href="{{ path('app_logout') }}">Logout</a></li>
                            </div>
                            <div class="mb-4">
                                <li><a class="btn btn-outline-warning" href="{{ path('home') }}">Page membre</a></li>
                            </div>
                        {% endif %}

                    </ol>

                </div>
            </div>
        </div>
        <!-- /.col-lg-12 -->
    </div>





    <div class="container-fluid">
        <h2>Liste des blogs</h2>
        <hr>
        <!--left-->
        {% for blog in blogs %}
            <p style="width:400px;">
            <div class="col-sm-10">
                <div class="icon-box">
                    <div class="row">

                        <div class=" col-md-4 ">
                        </div>
                        <div class=" col-md-8 " >
                            {{ blog.contenuBlog }}
                        </div>
                    </div>
                </div>
            </div>
        <div class="col-sm-3">

            <div class="icon-box">

                <div class="profile-pic">
                    <img src="{{asset('/uploads/' ~ blog.imageBlog)}}" alt="" width="450">
                </div>

                <h4><strong><font size="6"> {{ blog.titreBlog }}</font></strong></h4>
                 <strong> Publié par: </strong>
                 {{ blog.emailPublisher }}

                  <p>  <strong>  Crée le: </strong>
                  {{ blog.createdAt ? blog.createdAt|date('H:i') : '' }}
                {{ blog.createdAt ? blog.createdAt|date('Y-m-d') : '' }}
                {% if blog.updatedAt != blog.createdAt %}
                     <strong>/ modifié le: </strong>
                        {{ blog.updatedAt ? blog.updatedAt|date('H:i') : '' }}
                            {{ blog.updatedAt ? blog.updatedAt|date('Y-m-d') : '' }} </p>
                {% endif %}

            </div>
        </div>


            {{ include('blog/_delete_form.html.twig') }}
            <hr><!--/left-->
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        <!--center-->

    </div>
</div>
{% endblock %}

templates/blog_f/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Blog{% endblock %}

{% block body %}
    <h1>Create new Blog</h1>

    {{ include('blog_f/_form.html.twig') }}

    <a href="{{ path('app_blog_f_index') }}">back to list</a>
{% endblock %}

templates/blog_f/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Blog{% endblock %}

{% block body %}
    <h1>Blog</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id_blog</th>
                <td>{{ blog.idBlog }}</td>
            </tr>
            <tr>
                <th>Email_publisher</th>
                <td>{{ blog.emailPublisher }}</td>
            </tr>
            <tr>
                <th>Titre_blog</th>
                <td>{{ blog.titreBlog }}</td>
            </tr>
            <tr>
                <th>Contenu_blog</th>
                <td>{{ blog.contenuBlog }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ blog.createdAt ? blog.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>UpdatedAt</th>
                <td>{{ blog.updatedAt ? blog.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Image_blog</th>
                <td>{{ blog.imageBlog }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_blog_f_index') }}">back to list</a>

    <a href="{{ path('app_blog_f_edit', {'id_blog': blog.id_blog}) }}">edit</a>

    {{ include('blog_f/_delete_form.html.twig') }}
{% endblock %}